source 'https://cdn.cocoapods.org/'
source 'https://github.com/changjianfeishui/mht-specs'

use_frameworks!

platform :ios, '13.0'

target 'MHTLoginModel_Example' do
  pod 'MHTLoginModel', :path => '../'

  target 'MHTLoginModel_Tests' do
    inherit! :search_paths

    
  end
end
